apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alloy
    spec:
      serviceAccountName: alloy-sa  # Sử dụng SA đã tạo ở bước trước
      containers:
        - name: alloy
          image: grafana/alloy:latest
          args:
            - run
            - --storage.path=/var/lib/alloy/data
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345
          securityContext:
            runAsUser: 0 # Chạy quyền root để đọc log hệ thống trên Kind
          volumeMounts:
            - mountPath: /etc/alloy
              name: config
            - mountPath: /var/log
              name: varlog
              readOnly: true
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: alloy-config-final # Tên ConfigMap chứa file config.alloy của bạn
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers