apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: default
spec:
  # Không dùng ClusterIP khi dùng hostNetwork để tránh xung đột IP
  ports:
    - name: http-ui
      port: 12345
      targetPort: 12345
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
  selector:
    app.kubernetes.io/name: alloy