apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "nodes/proxy", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-binding
subjects:
  - kind: ServiceAccount
    name: alloy-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: alloy-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alloy
    spec:
      # QUAN TRỌNG: hostNetwork giúp giải quyết lỗi UNAVAILABLE trên Kind
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: alloy-sa
      containers:
        - name: alloy
          image: grafana/alloy:latest
          args:
            - run
            - --storage.path=/var/lib/alloy/data
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345
          ports:
            - name: http-ui
              containerPort: 12345
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /etc/alloy
              name: config
            - mountPath: /var/log
              name: varlog
              readOnly: true
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /var/lib/alloy/data
              name: storage
      volumes:
        - name: config
          configMap:
            name: alloy-config-final
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: storage
          emptyDir: {}